# Firebase Configuration
# Get these values from Firebase Console → Project Settings → General → Your apps

VITE_FIREBASE_API_KEY=AIzaSyCPjXXxZvGyM2fIM6h1ELgD1deCKqmh44s
VITE_FIREBASE_AUTH_DOMAIN=plv-ceit-classroom.firebaseapp.com
VITE_FIREBASE_PROJECT_ID=plv-ceit-classroom
VITE_FIREBASE_STORAGE_BUCKET=plv-ceit-classroom.firebasestorage.app
VITE_FIREBASE_MESSAGING_SENDER_ID=778516151085
VITE_FIREBASE_APP_ID=1:778516151085:web:4167392e64014a7cbc71a4

# Admin Emails (comma-separated list of emails that should have admin access)
# Users with these emails will automatically get admin role on first login
VITE_FIREBASE_ADMIN_EMAILS=admin@plv.edu.ph,registrar@plv.edu.ph
